### ISSUE TITLE
Persistent cpu usage when idle

### ISSUE THREAD

**Issue by genehand** [t0bst4r/matterbridge-home-assistant#119]
I noticed when using the plugin on a busy server (1800 entities), matterbridge cpu usage now hovers around 15%.  I also see an additional listener for `state_changed` on the HA `/developer-tools/event` page, which I think means it's being notified for all state changes then filtering out the ones we're interested in.  

I attempted to track that down in the code, sounds like [subscribeEntities](https://github.com/home-assistant/home-assistant-js-websocket/issues/271) may be a way to limit that from the HA side.

**Comment by t0bst4r** [comment]
As of now:

1. the home-assistant-adapter subscribes to all entities, because
  a. when a new device is added to HA or has lost the "hidden" attribute (legacy), it will be immediately be picked up
  c. when a device is removed or gets the attribute "hidden" (legacy), the device will be removed from matterbridge
2. the adapter also subscribes to the entity registry. It emits ALL entity registry data, whenever registry data is changed (visibility, conversation settings, add/remove of entity).
  a. when the hidden state of an entity changes, it gets added or removed from matterbridge

Of course, this requires a lot of data to be transferred between matterbridge and home assistant, but otherwise I would not be able to add new devices.

Possible solution:
1. initially fetch ALL entities and apply include/exclude patterns
2. subscribe to known entities only (remove those from the subscription which change to hidden or get removed)
3. new entities or those who change from hidden to not-hidden, will only be picked up after restarting matterbridge

**Comment by antoniozh** [comment]
Maybe the entity registry and also the subscription of visible devices could be configurable by a flag (included with a warning when a high device count is reached)?

**Comment by genehand** [comment]
I'm not super familiar with the HA internals, my assumption/guess is that the entity registry would track all the new/changed/hidden entities?  If that's the case, I'm thinking watching the registry could handle any entity changes, then separately subscribe only to known entities.  

That said, I'd be totally ok if some changes require restarting matterbridge.  I'm pretty used to this for HA discovery in general 😄

**Comment by t0bst4r** [comment]
I have changed the behaviour in Version `^2.0.0` to:
1. load all entities once at startup
2. apply the pattern / domain matcher
3. load the entity-registry once for the included entities
4. subscribe for included entity-states only

**Comment by genehand** [comment]
Looks like it did the trick 👍 

<img width="874" alt="Screenshot 2024-07-24 at 8 34 25 PM" src="https://github.com/user-attachments/assets/ee273777-6e9b-457c-be7c-ceafc224d4dc">
