### ISSUE TITLE
[Feature]: Support for temperature and humidity sensors

### ISSUE THREAD

**Issue by tammeryousef1006** [t0bst4r/matterbridge-home-assistant#209]
### Domain

sensor

### What is actually missing?

hi there , can you kindly add support for temp & humd sensor , many thanks in advance.

**Comment by t0bst4r** [comment]
Could you please provide some more details about the attributes and states of your entities?
Please go to the "developer tools" in home assistant. Open the "states" tab and search for one humidity and one temperature sensor.

Past the entity_id, current state and attributes here. 

E.g. like this:

![grafik](https://github.com/user-attachments/assets/bb324957-6c05-44c8-9c9d-81d0b7099654)

**Comment by tammeryousef1006** [comment]
![temp](https://github.com/user-attachments/assets/bbf94727-7938-4cde-8050-5965abb6671e)

**Comment by tammeryousef1006** [comment]
![door](https://github.com/user-attachments/assets/b94f78ad-7652-45d0-9726-82239d4deda4)

**Comment by tammeryousef1006** [comment]
![tuya](https://github.com/user-attachments/assets/3edc3cae-b486-4b88-b9e1-4d0dba46cb9a)

**Comment by pvanbuijtene** [comment]
Started to look into this.

@t0bst4r I have a lot of things working locally but I'm unable to find a solution for the `Error: Only supported EndpointInterface implementation is Endpoint` error.

How did you solve this? hope you're not publishing the package before testing 😅

**Comment by t0bst4r** [comment]
@pvanbuijtene 
we are speaking about local development, right?

The error message happens when `matterbridge-home-assistant` is using matterbridge from a different `node_modules` folder than the matterbridge package that is actually running.

For example this can happen when you have installed matterbridge globally, while adding the plugin from the local development environment to it.

How did you add the dev plugin and how did you start matterbridge? You could use `npm run run:matterbridge` at the root of the project. It will actually go into the nested package, build it, add it to matterbridge and run the locally installed matterbridge from the correct node_modules. 

if that is not working let’s add another issue to solve problems with local development to not spam this issue here.

**Comment by pvanbuijtene** [comment]
Local development indeed. Missed that part, got it working 👍

**Comment by t0bst4r** [comment]
Thanks to @pvanbuijtene this was released with `2.6.0`
