### ISSUE TITLE
Bug: Cannot connect to Google Home on IOS

### ISSUE THREAD

**Issue by Ultra-bob** [t0bst4r/matterbridge-home-assistant#93]
I've set up matterbridge and all my HA devices show up, but when trying to add it to Google Home with my iPhone, it fails. 
Debug logs attached (they didn't fit)
[matterbridge-logs.txt](https://github.com/user-attachments/files/15893678/matterbridge-logs.txt)

**Comment by t0bst4r** [comment]
I am not quite sure, why this is not working. I need to take some more time to search through the logs. 

Unfortunately I cannot test it locally since I don’t have a google home device.

> but when trying to add it to Google Home with my iPhone, it fails.

Could you provide more details on that? Any error you get from the google home app?

How do you execute Matterbridge? HA Addon, Docker or custom? Which version are you using?

**Comment by t0bst4r** [comment]
Could you maybe try the following:
1. open the web-ui (probably port 8283)
2. Navigate to settings and click "Reset Matterbridge Commissioning"
3. Try to pair again

**Comment by Ultra-bob** [comment]
I have already been factory resetting matterbridge between attempts, as my phone doesn't even seem to be able to connect otherwise

It's running on your docker image

When i try to add it, the IOS dialog appears, then loads for about a minute, then fails with an error and then google home says something went wrong

**Comment by Ultra-bob** [comment]
I have updated to the latest version, and tried disabling the matter-server container for home assistant, but neither works.
After commissioning is reset, the error is: "Unable to add accessory: You may need to restart your accessory before you can add it to your home", and a ton of logs are generated (attached initially). After that, the error is "Pairing Failed" and only these messages are generated
```
2024-06-19 21:22:48.358 INFO   FailsafeContext      Failsafe timer expired, Reset fabric builder.
2024-06-19 21:22:48.358 INFO   SecureSession        Register Session secure/16337 to send a close when exchange is ended.
```

**Comment by t0bst4r** [comment]
I just cannot find anything in the logs pointing me in the exact direction. I‘ll need to dive a lot deeper into the logs and the matter.js library for that. 

The only thing i found so far is that the matter pairing request from google home seems to come from an IPv6 address. The web ui is accessed from an IPv4 address. IPv6 should be supported by matter.js since it’s part of the matter specification, but it could be related to the docker configuration (maybe some parameter needs to be set or something else - I need to do further research for that).

Since I do not own any google home device, maybe @Cheerpipe could give it a try with the latest version and google home?
(Sorry for asking you for help, but I’ve seen in another ticket, that you got it working with google home). I just want to make sure if it’s a general issue or if it’s a problem with the setup of @Ultra-bob.

**Comment by Ultra-bob** [comment]
I'll try to set up IPv6 support in docker, and see if that fixes it

**Comment by t0bst4r** [comment]
Just a stupid question:
Did you use network mode "host", or did you map each port?

**Comment by Ultra-bob** [comment]
Network mode host

**Comment by Ultra-bob** [comment]
addding ipv6 did not help

**Comment by Ultra-bob** [comment]
Here is the full compose and config
```yaml
  matterbridge:
    image: ghcr.io/t0bst4r/matterbridge-home-assistant:latest
    restart: unless-stopped
    network_mode: host
    environment:
      CONFIG_FILE: "/config/config.json"
    volumes:
      - /home/ultrablob/homeassistant/config/matterbridge-config.json:/config/config.json
      - matterbridge-data:/root/.matterbridge
```

```json
{
  "homeAssistantUrl": "http://192.168.2.4:8123",
  "homeAssistantAccessToken": "***********",
  "homeAssistantClientConfig": {
    "includeDomains": ["light", "fan"]
  }
}
```

**Comment by t0bst4r** [comment]
Do you have any special (network) setup? Running on a VM? VLAN? Special proprietary switches or Routers?

**Comment by Ultra-bob** [comment]
Nope, just my old gaming pc wired into a switch connected to my isp router

**Comment by Ultra-bob** [comment]
Currently working on trying to disable IPv6 on my phone

**Comment by Ultra-bob** [comment]
The only other thing that could be wrong is this error
```
2024-06-20 17:43:04.489 INFO   UdpMulticastServer   wg0: send Unknown system error -126 224.0.0.251:5353
2024-06-20 17:43:04.546 INFO   UdpMulticastServer   wg0: send Unknown system error -126 224.0.0.251:5353
```
Which seems to indicate it is trying to send udp through my wireguard interface. Not sure if that's a problem or how to disable it on that interface

**Comment by Ultra-bob** [comment]
Closing this because discussion has moved over to the main matterbridge github
